import { ApplicationCommandOptionType } from 'discord-api-types/v9';

export default {
	name: 'pokeset',
	description: 'Set or remove the pokemon webhook configuration for a particular channel.',
	options: [
		{
			type: 7,
			name: 'channel',
			description: 'The channel to create the raid webhook for.',
			required: false,
			channel_types: [0],
		},
		{
			type: ApplicationCommandOptionType.Boolean,
			name: 'update',
			description: 'If true, existing config will be updated instead of overwritten.',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Number,
			name: 'latitude',
			description: 'The latitude to filter on with radius.',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Number,
			name: 'longitude',
			description: 'The longitude to filter on with radius.',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Number,
			name: 'radius',
			description: 'The radius (in km or m based on server configuration) to filter on from the given city or lat/long',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.String,
			name: 'unit',
			description: 'Radius metric: km (kilometres) | m (miles)',
			required: false,
			choices: [
				{ name: 'm', value: 'm' },
				{ name: 'km', value: 'km' },
			],
		},
		{ type: ApplicationCommandOptionType.String, name: 'city', description: 'The city to filter on', required: false },
		{
			type: ApplicationCommandOptionType.Boolean,
			name: 'boosted',
			description: 'Whether to filter on boosted',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'miniv',
			description: 'The mnimimum IV to filter on',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'maxiv',
			description: 'The maximum IV to filter on',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'mincp',
			description: 'The minimum cp to filter on',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'maxcp',
			description: 'The maximum cp to filter on',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'minlevel',
			description: 'The minimum level to filter on',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'maxlevel',
			description: 'The maximum level to filter on',
			required: false,
		},
		{ type: 5, name: 'train', description: 'Whether or not to filter on train', required: false },
		{
			type: ApplicationCommandOptionType.String,
			name: 'rmpokemon',
			description: 'Pokemon to remove from the filter, update must be true.',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.String,
			name: 'names',
			description: 'Comma separated Pokemon names to filter on.',
			required: false,
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'atkiv',
			description: 'The atk IV to filter on',
			required: false,
			choices: [
				{ name: '0', value: 0 },
				{ name: '1', value: 1 },
				{ name: '2', value: 2 },
				{ name: '3', value: 3 },
				{ name: '4', value: 4 },
				{ name: '5', value: 5 },
				{ name: '6', value: 6 },
				{ name: '7', value: 7 },
				{ name: '8', value: 8 },
				{ name: '9', value: 9 },
				{ name: '10', value: 10 },
				{ name: '11', value: 11 },
				{ name: '12', value: 12 },
				{ name: '13', value: 13 },
				{ name: '14', value: 14 },
				{ name: '15', value: 15 },
			],
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'defiv',
			description: 'The def IV to filter on',
			required: false,
			choices: [
				{ name: '0', value: 0 },
				{ name: '1', value: 1 },
				{ name: '2', value: 2 },
				{ name: '3', value: 3 },
				{ name: '4', value: 4 },
				{ name: '5', value: 5 },
				{ name: '6', value: 6 },
				{ name: '7', value: 7 },
				{ name: '8', value: 8 },
				{ name: '9', value: 9 },
				{ name: '10', value: 10 },
				{ name: '11', value: 11 },
				{ name: '12', value: 12 },
				{ name: '13', value: 13 },
				{ name: '14', value: 14 },
				{ name: '15', value: 15 },
			],
		},
		{
			type: ApplicationCommandOptionType.Integer,
			name: 'staiv',
			description: 'The sta IV to filter on',
			required: false,
			choices: [
				{ name: '0', value: 0 },
				{ name: '1', value: 1 },
				{ name: '2', value: 2 },
				{ name: '3', value: 3 },
				{ name: '4', value: 4 },
				{ name: '5', value: 5 },
				{ name: '6', value: 6 },
				{ name: '7', value: 7 },
				{ name: '8', value: 8 },
				{ name: '9', value: 9 },
				{ name: '10', value: 10 },
				{ name: '11', value: 11 },
				{ name: '12', value: 12 },
				{ name: '13', value: 13 },
				{ name: '14', value: 14 },
				{ name: '15', value: 15 },
			],
		},
	],
	default_permission: false,
} as const;
